# Generated by Django 4.2.16 on 2024-12-04 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinsnap', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinsnapWebhookState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=255, unique=True)),
                ('is_connected_to_webhook', models.BooleanField(default=False)),
            ],
        ),
    ]
