# Generated by Django 4.2.16 on 2024-12-09 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinsnap', '0002_coinsnapwebhookstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinsnapwebhookstate',
            name='secret',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
